# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JamIngest', '0002_auto_20160821_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jamsource',
            old_name='journal_name',
            new_name='source_name',
        ),
        migrations.AddField(
            model_name='jamsource',
            name='target_type',
            field=models.CharField(default='journal', max_length=300),
            preserve_default=False,
        ),
    ]
